# Generated 2025-08-27 from:
# /home/jacobala@alabsad.fau.de/New_speechbrain/speechbrain/recipes/CommonVoice/ASR/CTC/hparams/train_en_with_wav2vec.yaml
# yamllint disable
# ################################
# Model: wav2vec2 + DNN + CTC
# Augmentation: SpecAugment
# Authors: Titouan Parcollet 2021
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 123
__set_seed: !apply:speechbrain.utils.seed_everything [123]
output_folder: NewDataASCMixresults/wavlm_ctc_en/123
test_wer_file: NewDataASCMixresults/wavlm_ctc_en/123/wer_test.txt
save_folder: NewDataASCMixresults/wavlm_ctc_en/123/save
train_log: NewDataASCMixresults/wavlm_ctc_en/123/train_log.txt

# URL for the biggest Fairseq english wav2vec2 model.
wav2vec2_hub: microsoft/wavlm-large
wav2vec2_folder: NewDataASCMixresults/wavlm_ctc_en/123/save/wav2vec2_checkpoint

# Data files
data_folder: //home/jacobala@alabsad.fau.de/AOT/Obfuscation_Techniques/New_speechbrain/ASCdatamix15db # e.g, /localscratch/cv-corpus-5.1-2020-06-22/fr
train_tsv_file: /home/jacobala@alabsad.fau.de/AOT/Obfuscation_Techniques/New_speechbrain/ASCdatamix15db/train.tsv # Standard CommonVoice .tsv files
dev_tsv_file: //home/jacobala@alabsad.fau.de/AOT/Obfuscation_Techniques/New_speechbrain/ASCdatamix15db/dev.tsv # Standard CommonVoice .tsv files
test_tsv_file: /home/jacobala@alabsad.fau.de/AOT/Obfuscation_Techniques/New_speechbrain/ASCdatamix15db/test.tsv # Standard CommonVoice .tsv files
accented_letters: false
language: en # use 'it' for Italian, 'rw' for Kinyarwanda, 'en' for english
train_csv: NewDataASCMixresults/wavlm_ctc_en/123/save/train.csv
valid_csv: NewDataASCMixresults/wavlm_ctc_en/123/save/dev.csv
test_csv: NewDataASCMixresults/wavlm_ctc_en/123/save/test.csv
skip_prep: false # Skip data preparation

# We remove utterance slonger than 10s in the train/dev/test sets as
# longer sentences certainly correspond to "open microphones".
avoid_if_longer_than: 10.0

####################### Training Parameters ####################################

number_of_epochs: 30
optimizer_step_limit: 75000
lr: 1.0
lr_wav2vec: 0.0001
precision: fp16 # bf16, fp16 or fp32
sample_rate: 16000
ckpt_interval_minutes: 30 # save checkpoint every N min

# We use Dynamic Batching here as CV english is quite big.
# Or turn it off (but training speed will decrease)
dynamic_batching: false
max_batch_length_train: 200
max_batch_length_val: 50 # we reduce it as the beam is much wider (VRAM)
num_bucket: 200
shuffle: true # if true re-creates batches at each epoch shuffling examples.
batch_ordering: random
max_batch_ex: 256
num_workers: 4

dynamic_batch_sampler_train:
  max_batch_length: 200
  num_buckets: 200
  shuffle: true
  batch_ordering: random
  max_batch_ex: 256

dynamic_batch_sampler_valid:
  max_batch_length: 50
  num_buckets: 200
  shuffle: true
  batch_ordering: random
  max_batch_ex: 256

# If dynamic batching is False, we use these instead
batch_size: 12
test_batch_size: 4
sorting: ascending

dataloader_options:
  batch_size: 12
  num_workers: 4

test_dataloader_options:
  batch_size: 4
  num_workers: 6

# BPE parameters
token_type: char  # ["unigram", "bpe", "char"]
character_coverage: 1.0

####################### Model Parameters #######################################
# activation: !name:torch.nn.LeakyReLU
wav2vec_output_dim: 1024
dnn_neurons: 1024
freeze_wav2vec: false
freeze_feature_extractor: false
dropout: 0.1
warmup_steps: 500

# Outputs
output_neurons: 28  # BPE size, index(blank/eos/bos) = 0

# Decoding parameters
# Be sure that the bos and eos index match with the BPEs ones
blank_index: 0
bos_index: 1
eos_index: 2

# Decoding parameters
test_beam_search:
  blank_index: 0
  beam_size: 100
  beam_prune_logp: -12.0
  token_prune_min_logp: -1.2
  prune_history: false
  topk: 1
  alpha: 1.0
  beta: 0.5
    # To use n-gram LM for decoding, follow steps in README.md.
    # kenlm_model_path: none

#
# Functions and classes
#
epoch_counter: &id010 !new:speechbrain.utils.epoch_loop.EpochCounter

  limit: 30

############################## Augmentations ###################################

# Speed perturbation
speed_perturb: &id001 !new:speechbrain.augment.time_domain.SpeedPerturb
  orig_freq: 16000
  speeds: [95, 100, 105]

# Frequency drop: randomly drops a number of frequency bands to zero.
drop_freq: &id002 !new:speechbrain.augment.time_domain.DropFreq
  drop_freq_low: 0
  drop_freq_high: 1
  drop_freq_count_low: 1
  drop_freq_count_high: 3
  drop_freq_width: 0.05

# Time drop: randomly drops a number of temporal chunks.
drop_chunk: &id003 !new:speechbrain.augment.time_domain.DropChunk
  drop_length_low: 1000
  drop_length_high: 2000
  drop_count_low: 1
  drop_count_high: 5

# Augmenter: Combines previously defined augmentations to perform data augmentation
wav_augment: !new:speechbrain.augment.augmenter.Augmenter
  min_augmentations: 3
  max_augmentations: 3
  augment_prob: 1.0
  augmentations: [*id001, *id002, *id003]

############################## Models ##########################################

enc: &id005 !new:speechbrain.nnet.containers.Sequential
  input_shape: [null, null, 1024]
  linear1: !name:speechbrain.nnet.linear.Linear
    n_neurons: 1024
    bias: true
  bn1: !name:speechbrain.nnet.normalization.BatchNorm1d
  activation: !new:torch.nn.LeakyReLU
  drop: !new:torch.nn.Dropout
    p: 0.1
  linear2: !name:speechbrain.nnet.linear.Linear
    n_neurons: 1024
    bias: true
  bn2: !name:speechbrain.nnet.normalization.BatchNorm1d
  activation2: !new:torch.nn.LeakyReLU
  drop2: !new:torch.nn.Dropout
    p: 0.1
  linear3: !name:speechbrain.nnet.linear.Linear
    n_neurons: 1024
    bias: true
  bn3: !name:speechbrain.nnet.normalization.BatchNorm1d
  activation3: !new:torch.nn.LeakyReLU

# wav2vec2: &id004 !new:speechbrain.lobes.models.huggingface_transformers.wav2vec2.Wav2Vec2
#   source: microsoft/wavlm-large
#   output_norm: true
#   freeze: false
#   freeze_feature_extractor: false
#   save_path: results/wavlm_ctc_en/1234/save/wav2vec2_checkpoint

#####
# Uncomment this block if you prefer to use a Fairseq pretrained model instead
# of a HuggingFace one. Here, we provide an URL that is obtained from the
# Fairseq github for the multilingual XLSR.
#
#wav2vec2_url: https://dl.fbaipublicfiles.com/fairseq/wav2vec/xlsr_53_56k.pt
#wav2vec2: !new:speechbrain.lobes.models.fairseq_wav2vec.FairseqWav2Vec2
#    pretrained_path: !ref <wav2vec2_url>
#    output_norm: True
#    freeze: False
#    save_path: !ref <save_folder>/wav2vec2_checkpoint/model.pt
#####
wav2vec2: !new:speechbrain.lobes.models.huggingface_transformers.wav2vec2.Wav2Vec2
    source: !ref <wav2vec2_hub>
    output_norm: True
    freeze: True
    save_path: model_checkpoints
ctc_lin: &id006 !new:speechbrain.nnet.linear.Linear

  input_size: 1024
  n_neurons: 28

log_softmax: !new:speechbrain.nnet.activations.Softmax
  apply_log: true

ctc_cost: !name:speechbrain.nnet.losses.ctc_loss
  blank_index: 0

# modules:
#   wav2vec2: *id004
#   enc: *id005
#   ctc_lin: *id006
model: &id007 !new:torch.nn.ModuleList
- [*id005, *id006]
model_opt_class: !name:torch.optim.Adadelta
  lr: 1.0
  rho: 0.95
  eps: 1.e-8

wav2vec_opt_class: !name:torch.optim.AdamW
  lr: 0.0001
  weight_decay: 0.01

lr_annealing_model: &id008 !new:speechbrain.nnet.schedulers.NewBobScheduler
  initial_value: 1.0
  improvement_threshold: 0.0025
  annealing_factor: 0.8
  patient: 0

lr_annealing_wav2vec: &id009 !new:speechbrain.nnet.schedulers.NewBobScheduler
  initial_value: 0.0001
  improvement_threshold: 0.0025
  annealing_factor: 0.9
  patient: 0


asr_model: !new:torch.nn.ModuleList
    - [!ref <enc>, !ref <ctc_lin>]

tokenizer: !new:sentencepiece.SentencePieceProcessor

encoder: !new:speechbrain.nnet.containers.LengthsCapableSequential
    wav2vec2: !ref <wav2vec2>
    enc: !ref <enc>
    ctc_lin: !ref <ctc_lin>
    log_softmax: !ref <log_softmax>

decoding_function: !name:speechbrain.decoders.ctc_greedy_decode
    blank_id: !ref <blank_index>

modules:
    encoder: !ref <encoder>
    
pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
    loadables:
        wav2vec2: !ref <wav2vec2>
        asr: !ref <asr_model>
        tokenizer: !ref <tokenizer>
    paths:
        wav2vec2: /home/jacobala@alabsad.fau.de/New_speechbrain/speechbrain/recipes/CommonVoice/ASR/CTC/NewDataASCMixresults/wavlm_ctc_en/123/save/CKPT+2025-10-15+13-44-01+00/wav2vec2.ckpt
        asr: /home/jacobala@alabsad.fau.de/New_speechbrain/speechbrain/recipes/CommonVoice/ASR/CTC/NewDataASCMixresults/wavlm_ctc_en/123/save/CKPT+2025-10-15+13-44-01+00/model.ckpt
        tokenizer: /home/jacobala@alabsad.fau.de/New_speechbrain/speechbrain/recipes/CommonVoice/ASR/CTC/NewDataASCMixresults/wavlm_ctc_en/123/save/28_char.model

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
  checkpoints_dir: /home/jacobala@alabsad.fau.de/New_speechbrain/speechbrain/recipes/CommonVoice/ASR/CTC/NewDataASCMixresults/wavlm_ctc_en/123
  recoverables:
    #wav2vec2: *id004
    model: *id007
    scheduler_model: *id008
    scheduler_wav2vec: *id009
    counter: *id010
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
  save_file: /home/jacobala@alabsad.fau.de/New_speechbrain/speechbrain/recipes/CommonVoice/ASR/CTC/NewDataASCMixresults/wavlm_ctc_en/123/train_log.txt

error_rate_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats

cer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
  split_tokens: true